from __future__ import annotations

from typing import Any

SEARCH_RESULTS: dict[str, list[str]] = {
    "purchase order": [
        "List_PurchaseOrders_PAG30066",
        "Create_PurchaseOrder_PAG30066",
        "Modify_PurchaseOrder_PAG30066",
        "ReceiveAndInvoice_PurchaseOrders_PAG30066",
        "List_PurchaseOrderLines_PAG30067",
        "Create_PurchaseOrderLine_PAG30067",
        "List_PurchaseOrderLinesOfPurchaseOrder_PAG30067",
        "Create_PurchaseOrderLinesOfPurchaseOrder_PAG30067",
        "List_SalesOrders_PAG20028",
        "List_SustainabilityPurchaseLines_PAG6336",
        "List_SalesOrders_PAG30028",
        "List_PostedPurchaseInvoices_PAG9971",
        "List_PurchaseInvoices_PAG20042",
        "List_SalesOrderLines_PAG30044",
        "List_SalesOrderLinesOfSalesOrder_PAG30044",
        "List_PurchaseInvoiceLines_PAG30047",
        "List_PurchaseInvoiceLinesOfPurchaseInvoice_PAG30047",
        "List_PurchaseReceipts_PAG30064",
        "List_BufferIntercompanyInboxPurchaseLines_PAG30419",
        "List_BufferIntercompanyInboxPurchaseLinesOfIntercompanyOutgoingNotification_PAG30419",
    ],
    "purchase order line": [
        "List_PurchaseOrderLines_PAG30067",
        "Create_PurchaseOrderLine_PAG30067",
        "List_PurchaseOrderLinesOfPurchaseOrder_PAG30067",
        "Create_PurchaseOrderLinesOfPurchaseOrder_PAG30067",
        "List_SustainabilityPurchaseLines_PAG6336",
        "List_SalesOrderLines_PAG30044",
        "List_SalesOrderLinesOfSalesOrder_PAG30044",
        "List_PurchaseInvoiceLines_PAG30047",
        "List_PurchaseInvoiceLinesOfPurchaseInvoice_PAG30047",
        "List_BufferIntercompanyInboxPurchaseLines_PAG30419",
        "List_BufferIntercompanyInboxPurchaseLinesOfIntercompanyOutgoingNotification_PAG30419",
        "List_PurchaseReceiptLines_PAG30065",
        "List_PurchaseReceiptLinesOfPurchaseReceipt_PAG30065",
        "List_PurchaseOrders_PAG30066",
        "Create_PurchaseOrder_PAG30066",
        "Modify_PurchaseOrder_PAG30066",
        "ReceiveAndInvoice_PurchaseOrders_PAG30066",
        "List_VendorContractLines_PAG8047",
        "List_VendorContractLinesOfVendorContract_PAG8047",
        "List_CustomerContractLines_PAG8045",
    ],
    "vendor": [
        "List_Vendors_PAG20010",
        "List_VendorContractLines_PAG8047",
        "List_VendorContractLinesOfVendorContract_PAG8047",
        "List_VendorContracts_PAG8023",
        "List_VendorContractDeferrals_PAG8048",
        "List_VendorContractDeferralsOfVendorContractLines_PAG8048",
        "List_Vendors_PAG30010",
        "Create_Vendor_PAG30010",
        "List_Vendors_PAG36959",
        "List_PurchaseOrders_PAG30066",
        "Create_PurchaseOrder_PAG30066",
        "Modify_PurchaseOrder_PAG30066",
        "ReceiveAndInvoice_PurchaseOrders_PAG30066",
        "List_VendorPayments_PAG30060",
        "List_VendorPaymentsOfVendorPaymentJournal_PAG30060",
        "List_SustainabilityPurchaseLines_PAG6336",
        "List_ItemVariants_PAG20052",
        "List_ItemVariantsOfItem_PAG20052",
        "List_Vendors_PAG30308",
        "List_VendorPaymentJournals_PAG30061",
    ],
    "item": [
        "List_ItemLedgerEntries_PAG30069",
        "List_Items_PAG20008",
        "List_InventoryPostingGroups_PAG30096",
        "List_InventoryPostingGroupOfItem_PAG30096",
        "List_Items_PAG30008",
        "Create_Item_PAG30008",
        "Modify_Item_PAG30008",
        "List_PurchaseReceipts_PAG30064",
        "List_PurchaseReceiptLines_PAG30065",
        "List_PurchaseReceiptLinesOfPurchaseReceipt_PAG30065",
        "List_ItemVariants_PAG30052",
        "List_ItemVariantsOfItem_PAG30052",
        "List_Locations_PAG30076",
        "List_LocationOfSalesInvoiceLine_PAG30076",
        "List_LocationOfSalesOrderLine_PAG30076",
        "List_LocationOfSalesQuoteLine_PAG30076",
        "List_LocationOfSalesCreditMemoLine_PAG30076",
        "List_LocationOfPurchaseInvoiceLine_PAG30076",
        "List_LocationOfPurchaseOrderLine_PAG30076",
        "List_LocationOfPurchaseCreditMemoLine_PAG30076",
    ],
    "receipt": [
        "List_PurchaseReceipts_PAG30064",
        "List_PurchaseReceiptLines_PAG30065",
        "List_PurchaseReceiptLinesOfPurchaseReceipt_PAG30065",
        "List_IntercompanyInboxTransactions_PAG30411",
        "List_HandledIntercompanyInboxTransactions_PAG30400",
        "List_IntercompanyIncomingNotification_PAG30415",
        "List_BufferIntercompanyInboxTransactions_PAG30423",
        "List_BufferIntercompanyInboxTransactionsOfIntercompanyOutgoingNotification_PAG30423",
        "List_ItemLedgerEntries_PAG30069",
        "List_RetainedEarningsStatement_PAG20029",
        "List_BufferIntercompanyInboxPurchaseHeaders_PAG30420",
        "List_BufferIntercompanyInboxPurchaseHeadersOfIntercompanyOutgoingNotification_PAG30420",
        "List_RetainedEarningsStatements_PAG30029",
        "List_PdfDocument_PAG30056",
        "List_PdfDocumentOfSalesInvoice_PAG30056",
        "List_PdfDocumentOfSalesOrder_PAG30056",
        "List_PdfDocumentOfSalesQuote_PAG30056",
        "List_PdfDocumentOfSalesCreditMemo_PAG30056",
        "List_PdfDocumentOfPurchaseInvoice_PAG30056",
        "List_PdfDocumentOfProject_PAG30056",
    ],
    "inventory": [
        "List_Items_PAG20008",
        "List_Attachments_PAG20039",
        "List_AttachmentsOfJournalLine_PAG20039",
        "List_BufferIntercompanyCommentLines_PAG30416",
        "List_BufferIntercompanyCommentLinesOfIntercompanyOutgoingNotification_PAG30416",
        "List_IntercompanySetup_PAG30414",
        "List_EDocumentFileContent_PAG6119",
        "List_EDocumentFileContentOfEDocumentServiceStatus_PAG6119",
        "List_GeneralLedgerEntryAttachments_PAG20040",
        "List_IntercompanyDimensions_PAG30402",
        "List_ItemVariants_PAG20052",
        "List_ItemVariantsOfItem_PAG20052",
        "List_Features_PAG30092",
        "List_CreateQualityInspections_PAG20415",
        "List_HandledIntercompanyInboxTransactions_PAG30400",
        "List_EDocuments_PAG6112",
        "List_PostedESGReportLines_PAG6334",
        "List_ItemVariants_PAG30052",
        "List_ItemVariantsOfItem_PAG30052",
        "List_IntercompanyIncomingNotification_PAG30415",
    ],
}

ACTION_SCHEMAS: dict[str, dict[str, Any]] = {
    "List_PurchaseOrders_PAG30066": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "number",
            "orderDate",
            "postingDate",
            "vendorId",
            "vendorNumber",
            "vendorName",
            "requestedReceiptDate",
            "fullyReceived",
            "status",
            "lastModifiedDateTime",
        ],
        "notes": "Standard APIV2 purchase order list/read page.",
    },
    "Create_PurchaseOrder_PAG30066": {
        "required": [],
        "key_fields": [
            "orderDate",
            "postingDate",
            "vendorId",
            "vendorNumber",
            "payToVendorId",
            "payToVendorNumber",
            "shipToName",
            "purchaser",
            "requestedReceiptDate",
            "discountAmount",
        ],
        "notes": "Create-capable purchase order action.",
    },
    "Modify_PurchaseOrder_PAG30066": {
        "required": ["If-Match", "id"],
        "key_fields": [
            "id",
            "If-Match",
            "orderDate",
            "postingDate",
            "vendorId",
            "vendorNumber",
            "shipToName",
            "purchaser",
            "requestedReceiptDate",
            "discountAmount",
            "fullyReceived",
        ],
        "notes": "Requires @odata.etag concurrency token.",
    },
    "ReceiveAndInvoice_PurchaseOrders_PAG30066": {
        "required": ["id"],
        "key_fields": ["id", "select"],
        "notes": "Bound action discovered; no native receive-only sibling surfaced.",
    },
    "List_PurchaseOrderLines_PAG30067": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "documentId",
            "sequence",
            "lineType",
            "lineObjectNumber",
            "description",
            "quantity",
            "directUnitCost",
            "expectedReceiptDate",
            "receivedQuantity",
            "invoiceQuantity",
            "receiveQuantity",
            "locationId",
        ],
        "notes": "Includes the receiving fields needed for PO receipt preparation.",
    },
    "List_PurchaseOrderLinesOfPurchaseOrder_PAG30067": {
        "required": ["PurchaseOrder_id"],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "PurchaseOrder_id",
            "id",
            "documentId",
            "sequence",
            "lineObjectNumber",
            "description",
            "quantity",
            "directUnitCost",
            "receivedQuantity",
            "invoiceQuantity",
            "receiveQuantity",
        ],
        "notes": "Preferred native detail-read action for a single purchase order.",
    },
    "Create_PurchaseOrderLine_PAG30067": {
        "required": [],
        "key_fields": [
            "documentId",
            "sequence",
            "itemId",
            "accountId",
            "lineType",
            "lineObjectNumber",
            "description",
            "quantity",
            "directUnitCost",
            "expectedReceiptDate",
            "invoiceQuantity",
            "receiveQuantity",
            "locationId",
        ],
        "notes": "Standalone PO line create action.",
    },
    "Create_PurchaseOrderLinesOfPurchaseOrder_PAG30067": {
        "required": ["PurchaseOrder_id"],
        "key_fields": [
            "PurchaseOrder_id",
            "documentId",
            "sequence",
            "itemId",
            "lineType",
            "description",
            "quantity",
            "directUnitCost",
            "receiveQuantity",
        ],
        "notes": "Parent-scoped PO line create action.",
    },
    "List_Vendors_PAG30010": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "number",
            "displayName",
            "addressLine1",
            "city",
            "country",
            "phoneNumber",
            "email",
            "currencyCode",
            "blocked",
            "balance",
            "lastModifiedDateTime",
        ],
        "notes": "Standard APIV2 vendor page.",
    },
    "Create_Vendor_PAG30010": {
        "required": [],
        "key_fields": [
            "number",
            "displayName",
            "addressLine1",
            "city",
            "country",
            "phoneNumber",
            "email",
            "website",
            "currencyCode",
            "paymentTermsId",
            "paymentMethodId",
            "taxLiable",
            "blocked",
        ],
        "notes": "Vendor create action.",
    },
    "List_Vendors_PAG20010": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "number",
            "displayName",
            "address",
            "phoneNumber",
            "email",
            "website",
            "currencyCode",
            "blocked",
            "balance",
        ],
        "notes": "Legacy vendor list shape with flattened address.",
    },
    "List_Vendors_PAG30308": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "number",
            "displayName",
            "city",
            "state",
            "country",
            "currencyCode",
            "paymentTermsId",
            "paymentMethodId",
            "blocked",
            "balance",
        ],
        "notes": "Compact vendor projection.",
    },
    "List_Vendors_PAG36959": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "vendorNo",
            "vendorName",
            "address",
            "city",
            "postCode",
            "countryRegionCode",
            "vendorPostingGroup",
        ],
        "notes": "Alternate vendor projection with no GUID id.",
    },
    "List_Items_PAG30008": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "number",
            "displayName",
            "displayName2",
            "type",
            "itemCategoryCode",
            "blocked",
            "gtin",
            "inventory",
            "unitPrice",
            "unitCost",
            "baseUnitOfMeasureCode",
            "inventoryPostingGroupCode",
            "lastModifiedDateTime",
        ],
        "notes": "Standard APIV2 item page.",
    },
    "Create_Item_PAG30008": {
        "required": [],
        "key_fields": [
            "number",
            "displayName",
            "displayName2",
            "type",
            "itemCategoryCode",
            "blocked",
            "gtin",
            "inventory",
            "unitPrice",
            "unitCost",
            "baseUnitOfMeasureCode",
            "taxGroupCode",
            "generalProductPostingGroupCode",
            "inventoryPostingGroupCode",
        ],
        "notes": "Item create action.",
    },
    "Modify_Item_PAG30008": {
        "required": ["If-Match", "id"],
        "key_fields": [
            "id",
            "If-Match",
            "number",
            "displayName",
            "type",
            "blocked",
            "inventory",
            "unitPrice",
            "unitCost",
            "baseUnitOfMeasureCode",
        ],
        "notes": "Requires @odata.etag concurrency token.",
    },
    "List_Items_PAG20008": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "number",
            "displayName",
            "type",
            "itemCategoryCode",
            "blocked",
            "baseUnitOfMeasure",
            "inventory",
            "unitPrice",
            "unitCost",
            "lastModifiedDateTime",
        ],
        "notes": "Legacy item list shape.",
    },
    "List_PurchaseReceipts_PAG30064": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "number",
            "invoiceDate",
            "postingDate",
            "vendorNumber",
            "vendorName",
            "orderNumber",
            "currencyCode",
            "lastModifiedDateTime",
        ],
        "notes": "Read-only posted purchase receipt header page.",
    },
    "List_PurchaseReceiptLines_PAG30065": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "documentId",
            "sequence",
            "lineType",
            "lineObjectNumber",
            "description",
            "unitOfMeasureCode",
            "unitCost",
            "quantity",
            "expectedReceiptDate",
        ],
        "notes": "Read-only posted purchase receipt line page.",
    },
    "List_PurchaseReceiptLinesOfPurchaseReceipt_PAG30065": {
        "required": ["PurchaseReceipt_id"],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "PurchaseReceipt_id",
            "id",
            "documentId",
            "sequence",
            "lineType",
            "lineObjectNumber",
            "description",
            "unitCost",
            "quantity",
        ],
        "notes": "Preferred native detail-read action for a single posted receipt.",
    },
    "List_ItemLedgerEntries_PAG30069": {
        "required": [],
        "query_options": ["filter", "orderby", "select", "top", "skip", "resultFormat"],
        "key_fields": [
            "id",
            "entryNumber",
            "itemNumber",
            "postingDate",
            "entryType",
            "sourceNumber",
            "sourceType",
            "documentNumber",
            "documentType",
            "quantity",
            "costAmountActual",
        ],
        "notes": "Inventory history action, not an editable item journal API.",
    },
}

VALIDATED_READS: dict[str, dict[str, Any]] = {
    "purchase_orders_top5": {
        "action": "List_PurchaseOrders_PAG30066",
        "request": {
            "top": 5,
            "orderby": "lastModifiedDateTime desc",
            "select": (
                "id,number,vendorNumber,vendorName,status,orderDate,"
                "requestedReceiptDate,fullyReceived,lastModifiedDateTime"
            ),
        },
        "observed_total": 15,
        "sample_numbers": ["106030", "106029", "106028", "106027", "106026"],
    },
    "purchase_order_106030": {
        "action": "List_PurchaseOrders_PAG30066",
        "request": {
            "filter": "number eq '106030'",
            "select": (
                "id,number,vendorNumber,vendorName,status,orderDate,postingDate,"
                "requestedReceiptDate,fullyReceived,lastModifiedDateTime"
            ),
        },
        "observed_total": 1,
        "purchase_order_id": "9065b155-3b47-f111-a820-002248b5dea4",
    },
    "purchase_order_lines_106030": {
        "action": "List_PurchaseOrderLinesOfPurchaseOrder_PAG30067",
        "request": {
            "PurchaseOrder_id": "9065b155-3b47-f111-a820-002248b5dea4",
            "top": 20,
            "orderby": "sequence asc",
            "select": (
                "id,documentId,sequence,lineType,lineObjectNumber,description,quantity,"
                "directUnitCost,expectedReceiptDate,receivedQuantity,invoicedQuantity,"
                "invoiceQuantity,receiveQuantity,locationId"
            ),
        },
        "observed_total": 59,
        "sample_line_numbers": [10000, 20000, 30000],
    },
    "vendors_top5": {
        "action": "List_Vendors_PAG30010",
        "request": {
            "top": 5,
            "orderby": "lastModifiedDateTime desc",
            "select": (
                "id,number,displayName,country,phoneNumber,email,blocked,"
                "lastModifiedDateTime"
            ),
        },
        "observed_total": 8,
        "sample_numbers": ["V-HERSTERA", "64000", "82000", "50000", "40000"],
    },
    "items_top5": {
        "action": "List_Items_PAG30008",
        "request": {
            "top": 5,
            "orderby": "lastModifiedDateTime desc",
            "select": (
                "id,number,displayName,type,inventory,baseUnitOfMeasureCode,unitCost,"
                "lastModifiedDateTime"
            ),
        },
        "observed_total": 139,
        "sample_numbers": ["26904020", "27302019", "27303027", "27602024", "27601025"],
    },
    "purchase_receipts_top5": {
        "action": "List_PurchaseReceipts_PAG30064",
        "request": {
            "top": 5,
            "orderby": "lastModifiedDateTime desc",
            "select": (
                "id,number,orderNumber,vendorNumber,vendorName,postingDate,"
                "lastModifiedDateTime"
            ),
        },
        "observed_total": 239,
        "sample_numbers": ["107239", "107238", "107237", "107236", "107235"],
    },
    "purchase_receipt_lines_107239": {
        "action": "List_PurchaseReceiptLinesOfPurchaseReceipt_PAG30065",
        "request": {
            "PurchaseReceipt_id": "bd8d6e93-9029-f111-9f24-7ced8dad939a",
            "top": 20,
            "orderby": "sequence asc",
            "select": (
                "id,documentId,sequence,lineType,lineObjectNumber,description,quantity,"
                "unitCost,expectedReceiptDate"
            ),
        },
        "observed_total": 2,
        "sample_line_numbers": [10000, 20000],
    },
    "purchase_receipts_by_order_106030": {
        "action": "List_PurchaseReceipts_PAG30064",
        "request": {
            "filter": "orderNumber eq '106030'",
            "select": (
                "id,number,orderNumber,vendorNumber,vendorName,postingDate,"
                "lastModifiedDateTime"
            ),
        },
        "observed_total": 0,
        "notes": (
            "Do not assume orderNumber is reliably populated in CRONUS posted "
            "receipt data."
        ),
    },
}


def summarize_action(action_name: str) -> str:
    schema = ACTION_SCHEMAS[action_name]
    required = ", ".join(schema.get("required", [])) or "none"
    fields = ", ".join(schema.get("key_fields", []))
    return f"{action_name}: required={required}; key_fields={fields}"
