from __future__ import annotations

from unittest.mock import MagicMock, patch

from src.mcp.feature_flags_mcp.models import FlagOverride
from src.mcp.feature_flags_mcp.server import (
    document_matches_context,
    set_supplier_config,
    to_flag_value,
    to_supplier_config,
)


def test_document_matches_context_returns_true_for_matching_override() -> None:
    override = FlagOverride(match={"supplier_id": "SUP-1", "store_id": "MAD-01"}, value=True)

    assert document_matches_context(override, {"supplier_id": "SUP-1", "store_id": "MAD-01"}) is True


def test_document_matches_context_returns_false_for_non_matching_override() -> None:
    override = FlagOverride(match={"supplier_id": "SUP-1"}, value=True)

    assert document_matches_context(override, {"supplier_id": "SUP-2"}) is False


def test_to_flag_value_builds_typed_model() -> None:
    flag = to_flag_value(
        {
            "id": "triage.enabled",
            "flag_name": "triage.enabled",
            "value": True,
            "version": 3,
            "description": "Enable the triage agent",
            "overrides": [{"match": {"supplier_id": "SUP-1"}, "value": False}],
            "updated_at": "2026-05-04T12:00:00Z",
        }
    )

    assert flag.flag_name == "triage.enabled"
    assert flag.value is True
    assert flag.version == 3
    assert flag.overrides[0].match == {"supplier_id": "SUP-1"}


def test_to_supplier_config_builds_typed_model() -> None:
    supplier_config = to_supplier_config(
        {
            "id": "SUP-1",
            "supplier_id": "SUP-1",
            "configuration": {"auto_approve_eligible": True},
            "description": "Generated by learning.",
            "updated_at": "2026-05-04T12:00:00Z",
        }
    )

    assert supplier_config.supplier_id == "SUP-1"
    assert supplier_config.configuration["auto_approve_eligible"] is True


def test_set_supplier_config_upserts_supplier_document() -> None:
    container = MagicMock()
    container.upsert_item.return_value = {
        "id": "SUP-2",
        "supplier_id": "SUP-2",
        "configuration": {"recommended_tolerance_pct": 1.5},
        "description": "Generated by learning.",
        "updated_at": "2026-05-04T12:00:00Z",
    }

    with patch("src.mcp.feature_flags_mcp.server.get_flags_container", return_value=container):
        result = set_supplier_config(
            supplier_id="SUP-2",
            configuration={"recommended_tolerance_pct": 1.5},
            description="Generated by learning.",
        )

    container.upsert_item.assert_called_once()
    document = container.upsert_item.call_args.kwargs["body"]
    assert document["document_type"] == "supplier-config"
    assert result["supplier_id"] == "SUP-2"
